# Generated by Django 3.0.5 on 2020-04-27 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default=datetime.datetime(2020, 4, 27, 17, 11, 34, 709177, tzinfo=utc), upload_to='media'),
            preserve_default=False,
        ),
    ]
